Nowy tekst o cyklu jesiennych konferencji dla branży IT
techwriter-pl/techwriter-pl.github.io pull request #119
Opened 2024-09-09 10:49 UTC by morvenn

Do sprawdzenia

2024-09-09 11:06 UTC, docdeveloper requested changes

2024-09-09 11:06 UTC, docdeveloper commented on blog/konferencyjna-jesien-x-5/index.md
> +Każdej z konferencji będą towarzyszyły Wirtualne Targi Pracy. No i - jak to na podobnych wydarzeniach bywa - każde z nich jest świetną okazją, aby poszerzyć sieć kontaktów, poznać ciekawych ludzi i d
```suggestion
Każdej z konferencji będą towarzyszyły Wirtualne Targi Pracy. Ponadto, jak to na podobnych wydarzeniach bywa, każde z nich jest świetną okazją, aby poszerzyć sieć kontaktów i poznać ciekawych ludzi. My z pewnością skorzystamy z tej okazji, aby szerzyć świadomość istnienia tej pozornie niszowej dziedziny, jaką jest technical writing.
```

2024-09-09 11:06 UTC, docdeveloper commented on blog/konferencyjna-jesien-x-5/index.md
> +Konferencje odbywają się od września do grudnia. Rejestracja i udział są bezpłatne. Nic nie tracisz, a możesz zyskać kontakty, inspiracje i wiedzę. Polecamy!
```suggestion
Podsumujmy:

- Konferencje odbywają się **od września do grudnia**
- Rejestracja i udział są **bezpłatne**
- Warto dołączyć - nic nie tracisz, a możesz zyskać kontakty, inspiracje i wiedzę.

 Serdecznie zapraszamy w imieniu organizatorów!
```

2024-09-09 11:06 UTC, docdeveloper commented on blog/konferencyjna-jesien-x-5/index.md
> +Co jest lepsze od jednej konferencji? Pięć konferencji :-)
```suggestion
Co jest lepsze od jednej konferencji? Kilka darmowych konferencji :-)

```

2024-09-09 12:26 UTC, morvenn commented on static/img/cover/konferencyjna_jesien_x_5.jpg
Tak, został pobrany z pexels:
![obraz](https://github.com/user-attachments/assets/b70dc494-4393-43c4-8183-6c916d2a0279)

2024-09-10 09:17 UTC, morvenn commented on blog/konferencyjna-jesien-x-5/index.md
> +Oto lista konferencji, do których warto dołączyć:
To zdanie niewiele wnosi, to fakt, ale zostało dostawione celowo, bo jest wprowadzeniem po leadzie - jeśli ktoś wejdzie na stronę z całym tekstem i zobaczy listę konferencji, to może to być niejasne.

2024-09-13 02:55 UTC, docdeveloper approved these changes

2024-09-13 11:06 UTC, merged