V edycja studiow Komunikacja techniczna - trwa nabor
techwriter-pl/techwriter-pl.github.io pull request #123
Opened 2024-09-23 10:02 UTC by AGaworska

Nowy post: V edycja studiów Komunikacja techniczna - trwa nabór.

2024-09-23 16:08 UTC, pensjonatus requested changes

2024-09-23 16:08 UTC, pensjonatus commented on blog/v-edycja-studiow-komunikacja-techniczna-trwa-nabor/index.md
> +# Najważniejsze informacje
```suggestion
## Najważniejsze informacje
```

2024-09-23 16:08 UTC, pensjonatus commented on blog/v-edycja-studiow-komunikacja-techniczna-trwa-nabor/index.md
Proponuję dodać cover image, bo bez tego wyświetla się bez niczego na stronie domowej.

![image](https://github.com/user-attachments/assets/04de4572-f2ff-4b47-8000-677d59690940)

2024-09-23 16:17 UTC, morvenn commented on blog/v-edycja-studiow-komunikacja-techniczna-trwa-nabor/index.md
> +# Studia okiem absolwentów
Jak okiem to absolwenta, a jak absolwentów, to oczami.

2024-09-24 06:42 UTC, pensjonatus approved these changes

2024-09-24 06:47 UTC, merged