podsumowanie #22 i zapowiedz #23 meetcontentwro
techwriter-pl/techwriter-pl.github.io pull request #42
Opened 2023-10-08 14:47 UTC by monBon-Ton

Hej, nie wiem czy wszystko ogarnęłam, ale używanie VSC po Polsku to jest horror! Nie idźcie tą drogą :D 

mam nadzieję, że niczego nie namotałam ;) 
Jakby co, to jeszcze muszę potwierdzić nazwę firmy więc proszę o review ale jeszcze z merdżem się wstrzymajmy please.

Dzięki!

2023-10-08 16:32 UTC, JustynaKula commented
Ja nie mam uwag, dobrze się czyta. Zastanawiam się tylko nad linkami do profili na LinkedIn wymienianych osób... Dawać czy nie dawać? Hmm...

2023-10-08 17:15 UTC, monBon-Ton commented
> Ja nie mam uwag, dobrze się czyta. Zastanawiam się tylko nad linkami do profili na LinkedIn wymienianych osób... Dawać czy nie dawać? Hmm...
> Edit: Bo jak dawać, to czy zrobić z tego zasadę na przyszłość? To w sumie pytanie do wszystkich.

Aaah, no właśnie. W sumie to nie wiem jakie macie podejście? Ale chyba faktycznie, we wcześniejszych nie linkowalismy 🤔

Dzięki za review! 🙌

2023-10-08 18:48 UTC, docdeveloper requested changes
Dodałem dwa komentarze do tekstu.

2023-10-09 06:50 UTC, pensjonatus requested changes

2023-10-09 06:50 UTC, pensjonatus commented on blog/meet-content-wro-pazdziernik-2023/index.md
> +### Październik - Text (poprzednio LiveChat)
```suggestion
## Październik - Text (poprzednio LiveChat)
```

2023-10-09 06:50 UTC, pensjonatus commented on blog/meet-content-wro-pazdziernik-2023/index.md
> +#### **GDZIE I KIEDY**
```suggestion
### **GDZIE I KIEDY**
```

2023-10-09 06:50 UTC, pensjonatus commented on blog/meet-content-wro-pazdziernik-2023/index.md
> +### Wrzesień - Dolby
```suggestion
## Wrzesień - Dolby
```

2023-10-09 06:50 UTC, pensjonatus commented on blog/meet-content-wro-pazdziernik-2023/index.md
> +#### AI
```suggestion
### AI
```

2023-10-09 06:50 UTC, pensjonatus commented on blog/meet-content-wro-pazdziernik-2023/index.md
> +#### AI i Tech Comms
```suggestion
### AI i Tech Comms
```

2023-10-09 06:50 UTC, pensjonatus commented on blog/meet-content-wro-pazdziernik-2023/index.md
> +#### AI i NLP
```suggestion
### AI i NLP
```

2023-10-09 06:50 UTC, pensjonatus commented on blog/meet-content-wro-pazdziernik-2023/index.md
> +---
Przydałoby się na tym pliku odpalić Prettier. Jeśli masz zainstalowany dodatek Prettier Code Formatter, to po naciśnięciu Ctrl+S (CMD+S na Macu) plik się sformatuje.

Prettier podzieli długie linijki na krótsze, max 80 znaków.

2023-10-09 06:50 UTC, pensjonatus commented on blog/authors.yml
> +  url: https://www.linkedin.com/in/monika-mrozek/
Możesz też dodać Avatar z GitHuba. W pliku powyżej są przykłady.

2023-10-13 10:06 UTC, closed without merging