Add promo article for MeetContentKRK-17
techwriter-pl/techwriter-pl.github.io pull request #62
Opened 2023-11-20 09:02 UTC by bszwarc

- Added promo article
- Added image

2023-11-20 18:00 UTC, tomekprus reviewed
@bszwarc  Zostawiłem kilka drobnych komentarzy.

2023-11-21 05:05 UTC, bszwarc commented on blog/meet-content-krk-listopad-2023/index.md
> +Instytut Filologii Angielskiej jest najstarszą placówką anglistyczną w Polsce.
Wzięłam w sumie to z ich własnego opisu ale trochę poprawię :)

2023-11-21 05:06 UTC, bszwarc commented on blog/meet-content-krk-listopad-2023/index.md
> +zrozumieli żart nawet jezeli nie mogą zobaczyć mema.
Ja bym zostawiła, nie widzę w tym w sumie nic złego - mamy też taki opis po angielsku z abstraktu naszej prelegentki :)

2023-11-21 05:06 UTC, bszwarc commented on blog/meet-content-krk-listopad-2023/index.md
> +Osoby zainteresowane mogą dołączyć do MeetContent na Slacku, aby być na bieżąco
Zgodzę się, dodam.

2023-11-21 05:23 UTC, tomekprus approved these changes
dla mnie spoko

2023-11-21 06:20 UTC, docdeveloper commented on blog/meet-content-krk-listopad-2023/index.md
> +sprawić żeby wszyscy zrozumieli żart nawet jeżeli nie mogą zobaczyć mema.
```suggestion
sprawić, żeby wszyscy zrozumieli żart nawet jeżeli nie mogą zobaczyć mema.
```

2023-11-21 06:22 UTC, docdeveloper commented on blog/meet-content-krk-listopad-2023/index.md
> +w Polsce. Główne obiekty Wydziału zlokalizowane są w centrum Krakowa, w
```suggestion
w Polsce. Główne obiekty wydziału zlokalizowane są w centrum Krakowa, w
```

2023-11-21 06:37 UTC, pensjonatus approved these changes

2023-11-21 06:40 UTC, docdeveloper requested changes

2023-11-21 06:40 UTC, docdeveloper commented on blog/meet-content-krk-listopad-2023/index.md
> +P: Czy wydarzenie będzie nagrywane czy transmitowane na żywo? <br /> O: Na
```suggestion
P: Czy wydarzenie będzie nagrywane lub transmitowane na żywo? <br /> O: Na
```

2023-11-21 06:40 UTC, docdeveloper commented on blog/meet-content-krk-listopad-2023/index.md
> +chwilę obecną nie, stawiamy na spotkania na miejscu gdzie możesz osobiście
```suggestion
chwilę obecną nie. Stawiamy na spotkania na miejscu gdzie możesz osobiście
```

2023-11-21 06:40 UTC, docdeveloper commented on blog/meet-content-krk-listopad-2023/index.md
> +Osoby zainteresowane mogą dołączyć do MeetContent na Slacku, aby być na bieżąco
```suggestion
Osoby zainteresowane mogą dołączyć do MeetContent na [Slacku](https://meetcontent.slack.com/), aby być na bieżąco
```

2023-11-21 06:40 UTC, docdeveloper commented on blog/meet-content-krk-listopad-2023/index.md
> +organizatorów? <br /> O: Możesz napisać do nas na Slacku, będziemy monitorować
```suggestion
organizatorów? <br /> O: Możesz napisać do nas na Slacku.
```

2023-11-21 06:40 UTC, docdeveloper commented on blog/meet-content-krk-listopad-2023/index.md
> +kanał przez pierwsze 30 minut od rozpoczęcia wydarzenia.
```suggestion
Podczas każdego wydarzenia, przez pierwsze 30 minut od rozpoczęcia na bieżąco sprawdzamy wiadomości na naszym kanale .
```

2023-11-21 15:06 UTC, docdeveloper approved these changes

2023-11-21 15:28 UTC, merged