Article about post graduate studies at Vistula
techwriter-pl/techwriter-pl.github.io pull request #63
Opened 2023-11-20 12:34 UTC by tomekprus

Promo blog on post graduate studies at Vistula. I added one term to the term bank.

2023-11-20 18:22 UTC, docdeveloper commented on blog/wystartowała czwata edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +Kolejny rok objęliśmy patronatem kierunek
```suggestion
Kolejny rok z rzędu objęliśmy patronatem kierunek 
```

2023-11-20 18:23 UTC, docdeveloper commented on blog/wystartowała czwata edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +- [po pierwszym semestrze](http://techwriter.pl/komunikacja-techniczna-jak-sie-studiuje/),
```suggestion
- [po pierwszym semestrze](http://techwriter.pl/komunikacja-techniczna-jak-sie-studiuje/)
```

2023-11-20 18:23 UTC, docdeveloper commented on blog/wystartowała czwata edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +- [po drugim semestrze](http://techwriter.pl/komunikacja-techniczna-drugi-semestr/).
```suggestion
- [po drugim semestrze](http://techwriter.pl/komunikacja-techniczna-drugi-semestr/)
```

2023-11-20 18:23 UTC, docdeveloper commented on blog/wystartowała czwata edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +Warto podkreślić, e w programie znajduje się pełny kurs przygotowujący do certyfikacji ITCQF – koszt szkolenia na wolnym
```suggestion
Warto podkreślić, że w programie znajduje się pełny kurs przygotowujący do certyfikacji ITCQF – koszt szkolenia na wolnym
```

2023-11-20 19:11 UTC, docdeveloper commented on blog/wystartowała czwata edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +Polsce i na świecie. Nadal mona dołączyć.
```suggestion
Polsce i na świecie. Nadal można dołączyć.
```

2023-11-20 19:11 UTC, docdeveloper commented on blog/wystartowała czwata edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +- Sposoby pozyskiwania informacji źródłowych.
```suggestion
- Sposoby pozyskiwania informacji źródłowych
```

2023-11-20 19:12 UTC, docdeveloper commented on blog/wystartowała czwata edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +- Audyt istniejącej dokumentacji.
```suggestion
- Audyt istniejącej dokumentacji
```

2023-11-20 19:12 UTC, docdeveloper commented on blog/wystartowała czwata edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +- Github pages
```suggestion
- Github Pages
```

2023-11-20 19:12 UTC, docdeveloper commented on blog/wystartowała czwata edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +- Publikowanie strony na GitHub Pages.
```suggestion
- Publikowanie strony na GitHub Pages
```

2023-11-20 19:13 UTC, docdeveloper commented on blog/wystartowała czwata edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +- Wprowadzenie do statycznych generatorów stron.
```suggestion
- Wprowadzenie do statycznych generatorów stron
```

2023-11-20 19:14 UTC, docdeveloper commented on blog/wystartowała czwata edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +- Wstęp do DITA, narzędzie oXygen XML editor
```suggestion
- Wstęp do DITA, narzędzie Oxygen XML Editor
```

2023-11-20 19:14 UTC, docdeveloper commented on blog/wystartowała czwata edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +- Prezentacje końcowe projektów.
```suggestion
- Prezentacje końcowe projektów
```

2023-11-20 19:16 UTC, docdeveloper commented on blog/wystartowała czwata edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +Kadrę zasilił Lance'a Cummings znany z corocznych wystąpień na konferencji Soap!. Wykładowcy to tylko i wyłącznie praktycy, którzy
```suggestion
Kadrę zasilił Lance'a Cummings znany z corocznych wystąpień na [konferencji soap!](https://soapconf.com/). Wykładowcy to tylko i wyłącznie praktycy, którzy
```

2023-11-20 20:38 UTC, tomekprus reviewed
Dzięki za feedback @docdeveloper!

2023-11-20 20:46 UTC, tomekprus commented
Zmiany od Michała + 3 znalezione przeze mnie literówki poprawione.

2023-11-20 21:18 UTC, morvenn commented on blog/wystartowała czwarta edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +Kadrę zasilił Lance'a Cummings znany z corocznych wystąpień na [konferencji soap!](https://soapconf.com/). Wykładowcy to tylko i wyłącznie praktycy, którzy
```suggestion
Kadrę zasilił Lance Cummings, znany z corocznych wystąpień na [konferencji soap!](https://soapconf.com/). Wykładowcy to tylko i wyłącznie praktycy, którzy
```

2023-11-20 21:20 UTC, morvenn commented on blog/wystartowała czwarta edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +narzędzi wykorzystywanych przez profesjonalnych technical writerów. Komunikacja na studiach odbywa się na Confluence a wszystkie zadania śledzone są w Jira. Zajęcia prowadzone są na platformie Micros
```suggestion
narzędzi wykorzystywanych przez profesjonalnych technical writerów. Komunikacja na studiach odbywa się na Confluence, a wszystkie zadania śledzone są w Jira. Zajęcia prowadzone są na platformie Microsoft Teams. Projekty tworzone są przy użyciu MadCap Flare, Oxygena, czy narzędzi i technik wspierających DocAsCode.
```

2023-11-20 21:29 UTC, morvenn commented on blog/wystartowała czwarta edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +przewidzieli 170 godzin wykładów i warsztatów. Każdy absolwent studiów będzie miał możliwość
```suggestion
Zajęcia trwają dwa semestry i kosztują 6800 zł. Na oba semestry organizatorzy
przewidzieli 170 godzin wykładów i warsztatów. Każdy absolwent studiów będzie miał możliwość
```

2023-11-20 21:30 UTC, morvenn commented on blog/wystartowała czwarta edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +Jeśli ukończyliście podobne kierunki studiów dajcie znać w komentarzu jakie są Wasze wrażenia i doświadczenia.
```suggestion
Jeśli ukończyliście podobne kierunki studiów, dajcie znać w komentarzu, jakie są Wasze wrażenia i doświadczenia. 
```

2023-11-20 21:33 UTC, morvenn requested changes
Zasugerowałam drobne poprawki z zakresu interpunkcji i składni zdań :-)

2023-11-20 22:52 UTC, tomekprus commented
@morvenn dzięki za komenty!

2023-11-21 06:50 UTC, docdeveloper requested changes

2023-11-21 06:50 UTC, docdeveloper commented on blog/wystartowała czwarta edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +koleżanki Magdy, która jest już absolwentką tego kierunku i dzieli się swoimi
```suggestion
koleżanki Magdy, absolwentki tego kierunku, która dzieli się swoimi
```

2023-11-21 06:50 UTC, docdeveloper commented on blog/wystartowała czwarta edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +Prowadzący nieustannie dostosowują program odpowiadając na feedback studentów. Zwiększono liczbę praktycznych zajęć w pierwszym semestrze oraz wprowadzono zajęcia z pisania przy użyciu AI. Studenci b
```suggestion
W odpowiedzi na opinie studentów, prowadzący nieustannie starają się modyfikować program studiów dopasowując go do aktualnych potrzeb. Przykładowo, zwiększono liczbę praktycznych zajęć w pierwszym semestrze oraz wprowadzono zajęcia z pisania przy użyciu AI. Studenci będą mogli dzięki temu więcej czasu w drugim semestrze poświęcić na projekt końcowy, który będzie ich wizytówką i głównym elementem ich profesjonalnego portfolio.
```

2023-11-21 06:50 UTC, docdeveloper commented on blog/wystartowała czwarta edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +Warto podkreślić, że w programie znajduje się pełny kurs przygotowujący do certyfikacji ITCQF – koszt szkolenia na wolnym
```suggestion
Warto podkreślić, że w programie znajduje się pełny kurs przygotowujący do certyfikacji ITCQF. Koszt takiego szkolenia na wolnym
```

2023-11-21 06:50 UTC, docdeveloper commented on blog/wystartowała czwarta edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +rynku to właściwie połowa kosztu całych studiów. Naszym zdaniem stosunek jakości
```suggestion
rynku to praktycznie połowa kosztu całych studiów. Biorąc to pod uwagę, stosunek jakości
```

2023-11-21 06:50 UTC, docdeveloper commented on blog/wystartowała czwarta edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +do ceny przedstawia się bardzo korzystnie.
```suggestion
do ceny studiów przedstawia się bardzo korzystnie.
```

2023-11-21 06:50 UTC, docdeveloper commented on blog/wystartowała czwarta edycja studiow-podyplomowych-komunikacja-techniczna/index.md
> +Jeśli ukończyliście podobne kierunki studiów, dajcie znać w komentarzu, jakie są Wasze wrażenia i doświadczenia.
```suggestion
Jeśli ukończyliście podobne kierunki studiów, dajcie znać w komentarzu jakie są Wasze wrażenia i doświadczenia. 
```

2023-11-21 07:47 UTC, tomekprus reviewed
Michal's comments were introduced.

2023-11-21 12:03 UTC, tomekprus reviewed
Wszystkie zmiany wprowadzone. Mogę to merge'ować?

2023-11-21 12:33 UTC, morvenn approved these changes

2023-11-22 10:08 UTC, docdeveloper approved these changes

2023-11-22 11:18 UTC, merged